# Usar una imagen base de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# INSTALAR FFMPEG 
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    apt-get clean

# Copiar los archivos de requisitos e instalarlos
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código de tu proyecto
COPY . .

# Crear carpetas necesarias
RUN mkdir -p uploads outputs

# Exponer el puerto
EXPOSE 8000

# Comando para iniciar la aplicación
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]